dist: bionic
language: node_js
node_js:
    - 12.11.0
before_script:
    - sudo apt update
    - sudo apt install build-essential libreadline-dev libnanomsg-dev lua5.3 liblua5.3-dev torch-trepl lua-torch-nn
    - npm install
    - npm run-script build
script:
    - npm run-script test
