dist: bionic
language: node_js
node_js:
    - 12.11.0
before_script:
    - sudo apt install build-essential libreadline-dev
    - curl -R -O http://www.lua.org/ftp/lua-5.3.4.tar.gz
    - tar -zxf lua-5.3.4.tar.gz
    - cd lua-5.3.4
    - make linux test
    - sudo make install
    - cd ..
    - wget https://luarocks.org/releases/luarocks-3.3.1.tar.gz
    - tar zxpf luarocks-3.3.1.tar.gz
    - cd luarocks-3.3.1
    - ./configure
    - make && make install
    - cd ..
    - npm install
    - npm run-script build
script:
    - npm run-script test
