dist: precise
language: node_js
node_js:
    - 12.11.0
before_script:
    - sudo apt update
    - sudo apt install build-essential libreadline-dev libnanomsg-dev lua5.3 liblua5.3-dev
    - git clone https://github.com/torch/distro.git ./torch --recursive
    - cd ./torch
    - bash install-deps
    - ./install.sh
    - cd ..
    - npm install
    - npm run-script build
script:
    - npm run-script test
